source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Socket.IO-Client-Swift', '~> 6.1.1' # Or latest version
pod 'MJExtension', '~>3.0.10'
pod 'JSQMessagesViewController'
pod 'AFNetworking', '~>3.1.0'
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'

