source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Socket.IO-Client-Swift', '~> 6.1.1' # Or latest version
pod 'MJExtension', '~>3.0.10'
pod 'JSMessagesViewController', '~> 4.0.5'
pod 'AFNetworking', '~>3.1.0'

